name: Python CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          pytest tests/

      - name: Zip source files
        run: |
          mkdir output
          cp -r src/ output/
          cp requirements.txt output/
          zip -r build.zip output

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-zip
          path: build.zip

      - name: Send Email Notification
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          to: your.receiver@example.com
          from: "extraordinarytechy@gmail.com"
          subject: "Python Build and Test Passed"
          body: |
            Python project build and test completed successfully.

            Tests passed.
            Artifact 'build.zip' has been uploaded.
          secure: true